### ISSUE TITLE
Abnormal molecule structure

### ISSUE THREAD

**Issue by Yujikaiya** [doyle-lab-ucla/auto-qchem#2]
I installed auto-qchem according to installation instructions (Windows), and run example notebook "framework_functionality_test.ipynb", but generated chemical structure is highly distorted.

![image](https://user-images.githubusercontent.com/31213500/128335238-53d53146-6c56-4cb1-8eed-57548ea29dce.png)

Is it common error when using Openbabel for molecular conformation generaion??
(I do not have experience using Openbabel for such purpose.)

How can I fix it?? (Installing different version of OpenBabel or using Linux instead of Windows?)

Here is my environment.
- openbabel v2.4.1
- Python 3.7

**Comment by zuranski** [comment]
Hello, 

The structure does not look normal. This sometimes happens when the python wrapper is installed, but it does not point to an installation of openbabel in the Windows system.

To check that please verify that BABEL_DATADIR points to an actual installation
```
import os
os.environ['BABEL_DATADIR']
```

If not, please remove the openbabel from conda, intall openbabel for Windows from https://github.com/openbabel/openbabel/releases/tag/openbabel-2-4-1 and reinstall openbabel in conda.

**Comment by Yujikaiya** [comment]
Thank you very much!!
Maybe I installed python wrapper first and that was the problem.

I could not fix it even though I removed openbabel from conda and reinstalled it, but I fixed by manually setting enviroment variable in notebook with codes below.

`import os`
`os.environ['BABEL_DATADIR'] = r"C:\Users\xxxx\AppData\Roaming\OpenBabel-2.4.1\data"`

The directry of 'BABEL_DATADIR' was found by using windwos command prompt with command below.

`echo %BABEL_DATADIR%`

Finally I can get the reasonable structure!

![image](https://user-images.githubusercontent.com/31213500/128985518-b3dbb84c-9874-4f47-be19-c95368b9d0d7.png)
